### ISSUE TITLE
Very cool tool, looking forward to using it. Few Q's

### ISSUE THREAD

**Issue by jeremyjpj0916** [gamunu/cassandra_snapshotter#3]
Thanks for taking time to make some docs about restore process! Can't wait to try this out within our company for Cassandra backup/restore from an internal S3 compatible offering.

Few questions for you if you have a moment:

1. I already saw in the utils.py the static the S3_CONNECTION_HOSTS, I went ahead and added our internal host names for connections. Is this all you can think of I would need to add/modify to make this compatible with internal S3 compliant Object Storage?

2. I am a python #newb , if I intend to install this without pip(since I needed to modify the source with my host names), copy the source code down to a dir. Then I was going to follow this - 
https://stackoverflow.com/questions/13270877/how-to-manually-install-a-pypi-module-without-pip-easy-install , where I will have in a dir setup.py and cassandra_snap dir beside it with all core files, then will run python setup.py install. Does this sound like it will work for this python app?

3. Lastly, we run Python 2.7.5, is this app meant for python3 or will our version of python be fine?

Thanks!
-Jeremy

**Comment by gamunu** [comment]
1. Notice below, It uses boto3 library to get the S3 bucket. So probably you will have to proxy the requests. i.e host entries or dns. https://github.com/gamunu/cassandra_snap/blob/80127ad34e6aedce7d304a752fad41bf591bd575/cassandra_snap/snapshotting.py#L137
2. Yes. It should work out of the box.
3. Our current setup uses python 2.7 so no issues there.

**Comment by jeremyjpj0916** [comment]
@gamunu Thank you so much for the helpful info, will attempt to get it working today and let you know how it goes. I read on other git issue it uses Password-less login with SSH keys between the node running the script and the Cassandra nodes themselves so will get that going and try to see if I can do a backup as well as restore from a backup 💯 !

**Comment by jeremyjpj0916** [comment]
@gamunu  My research of Cassandra has led me to this conclusion.

Cassandra supports full snapshots and incremental backups. Which to use really depends on how often you need to backup and the size of the data.

Our use case involves working with MB sized keyspaces and not so much large data so I feel once daily full snapshots would be feasible. And then restore from the full snapshot if needed.

My reading also led me to research taking snapshots is simply not enough, in the even the the schema has changed due to an application upgrade that the changed schema then broke functionality within the app itself OR a full cluster loss you need to have stored that old schema to restore your snapshot too.

Does this application support storing the schema at a place in time in the S3 as well? Or is this something you have been interested to implement? If not I would like to add it if you have some guidelines about where to put the code and utilize the S3 connection logic in place. I imagine it will go like so:
1. cqlsh -e "DESC KEYSPACE mykeyspace" > mykeyspace_schema.cql one one of the nodes of the cluster then putting this on S3 in a programmatic path that can be pulled later.

2. In the event the "app upgrade schema change" broke things, or database loss we will now need to run: source 'mykeyspace_schema.cql' on the node w cqlsh to restore the key space schema(which maybe has to delete the keyspace if it exists currently if that's a requirement of Cassandra(app upgrade schema change break specifically), then restore the keyspace. THEN once the schema is restored with that keyspace we can use the snapshots taken during the time that matched that keyspace schema backup.


EDIT

So my application I realized has a "migrations" operation that can setup the schema from a specific version of the app on an empty keyspace. So MAYBE best practice would probably just let this tool focus on snapshots and in the event i need to roll back schema DELETE the keyspace as it stands in the cluster. Remake it with the migrations and then import the snapshot data on the new empty remade keyspace. What are your thoughts there, sound like the right approach?

**Comment by jeremyjpj0916** [comment]
Figured my game plan out here. But am running into problems will make new topic with further errors.
