### ISSUE TITLE
Cassandra-snapshotter error

### ISSUE THREAD

**Issue by EmViKay** [gamunu/cassandra_snapshotter#7]
Hi!
Installed Cassandra-snapshotter on 3 linux machine.
Have error on all machine

~$ cassandra-snapshotter
Traceback (most recent call last):
  File "/usr/local/bin/cassandra-snapshotter", line 7, in <module>
    from cassandra_snap.main import main
  File "/usr/local/lib/python2.7/dist-packages/cassandra_snap/main.py", line 5, in <module>
    from fabric.api import env
ImportError: No module named api

Could you help?

**Comment by EmViKay** [comment]
python -V
Python 2.7.12

**Comment by EmViKay** [comment]
Fixed
need to install 
pip install fabric==1.13.1

**Comment by ndamclean** [comment]
Why is this closed? The posted solution is a workaround, not a fix.

The `setup.py` file needs to be updated  to specify the actual required verision of `fabric`.
